
services:
  parser:
    build: .
    container_name: car_parser
    restart: always
    environment:
      - NODE_ENV=production
      - DOCKER=true
      # Настройки подключения к внешней БД (можно переопределить через .env)
      - DB_HOST=${DB_HOST:-194.87.130.217}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-auto_db}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-P@rs3r_S3cR3t!}
      - DATABASE_URL=${DATABASE_URL:-postgresql://root:P@rs3r_S3cR3t!@194.87.130.217:5432/auto_db}
      # Настройки Telegram
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-8549893076:AAGhhljKJL7x_HolIrD6QRrp8nd1nUUJe_c}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:--1003636427966}
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]